// Builds tests/fixtures/release/: small slices of the real pinned release, with their own manifest, check values and
// pin, so the offline tests exercise the same verification chain as production. Run: npm run fixtures
import { readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { Db, int } from "../src/db.js";
import { DEFAULT_PIN, Release, defaultCacheDir, githubSource, sha256 } from "../src/release.js";

const OUT = join(import.meta.dirname, "..", "tests", "fixtures", "release");

/** Each code earns its place by the case it exercises. */
export const FIXTURE_CODES = {
  "99213": "all three hospitals; NM publishes no contracted dollar rate, only percent-derived and algorithm rows",
  "99214": "all three hospitals, outpatient and both settings",
  "70553": "MRI brain: description search (find_codes)",
  "73721": "MRI lower-extremity joint: description search (find_codes)",
  J1885: "HCPCS drug code",
  "470": "MS-DRG, inpatient only",
  "10011": "published by UChicago only",
  "12002": "the 'both' setting at Rush and UChicago",
} as const;

const release = new Release(DEFAULT_PIN, githubSource(DEFAULT_PIN.tag), defaultCacheDir());
const db = await Db.open(release);
const real = await release.manifest();

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });
const codes = Object.keys(FIXTURE_CODES).map((c) => `'${c}'`).join(", ");
const slices: Record<string, string> = {
  agg_code_prices: `SELECT * FROM agg_code_prices WHERE code IN (${codes}) ORDER BY ALL`,
  files: `SELECT * FROM files ORDER BY hospital_id`,
};

const files = [];
const tables: Record<string, { key: string[]; rows: number; distinct_keys: number }> = {};
for (const [table, sql] of Object.entries(slices)) {
  const path = join(OUT, `${table}.parquet`).replaceAll("\\", "/");
  await db.query([table as "agg_code_prices" | "files"], `COPY (${sql}) TO '${path}' (FORMAT parquet, COMPRESSION zstd)`);
  const rows = int((await db.query([], `SELECT count(*) AS n FROM read_parquet('${path}')`))[0]?.["n"]);
  const bytes = new Uint8Array(await readFile(path));
  files.push({ file: `${table}.parquet`, rows, bytes: bytes.length, sha256: sha256(bytes) });
  const realCv = (await release.checkValues()).tables[table];
  tables[table] = { key: realCv?.key ?? [], rows, distinct_keys: rows };
}

const checkValues = JSON.stringify({ tables, derived: {} }, null, 2) + "\n";
await writeFile(join(OUT, "check_values.json"), checkValues);
const manifest =
  JSON.stringify(
    {
      fingerprint: `fixture-of-${real.fingerprint}`,
      inputs: { price_files: real.inputs.price_files, nppes_files: real.inputs.nppes_files },
      files,
      check_values_sha256: sha256(new TextEncoder().encode(checkValues)),
    },
    null,
    2,
  ) + "\n";
await writeFile(join(OUT, "manifest.json"), manifest);

const pin = { tag: `fixture-${DEFAULT_PIN.tag}`, manifestSha256: sha256(new TextEncoder().encode(manifest)) };
await writeFile(
  join(import.meta.dirname, "..", "tests", "fixtures", "pin.ts"),
  `// Generated by scripts/make-fixtures.ts — do not edit. Regenerate when the default pin moves.\n` +
    `import type { ReleasePin } from "../../src/release.js";\n\n` +
    `export const FIXTURE_PIN: ReleasePin = ${JSON.stringify(pin, null, 2)};\n` +
    `export const FIXTURE_CODES = ${JSON.stringify(Object.keys(FIXTURE_CODES))} as const;\n`,
);
db.close();
console.error(`fixtures written: ${files.map((f) => `${f.file} (${f.rows} rows)`).join(", ")}; pin ${pin.manifestSha256}`);
