// Runs the mutation catalogue (scripts/mutations.ts): for each mutant, apply → type-check → run every suite → restore.
// Writes docs/results/mutations.json and docs/results/contract-tests.md. npm run mutate [-- MUTATION_ID ...]
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { MUTATIONS, type Mutation } from "./mutations.js";

const ROOT = join(import.meta.dirname, "..");
const RESULTS = join(ROOT, "docs", "results");
const npx = process.platform === "win32" ? "npx.cmd" : "npx";

interface VitestJson {
  numTotalTests: number;
  numPassedTests: number;
  numFailedTests: number;
  testResults: { name: string; assertionResults: { fullName: string; status: string }[] }[];
}

function vitest(): VitestJson {
  const dir = mkdtempSync(join(tmpdir(), "cpm-mutate-"));
  const out = join(dir, "report.json");
  spawnSync(npx, ["vitest", "run", "--reporter=json", `--outputFile=${out}`], { cwd: ROOT, shell: true, stdio: "ignore" });
  try {
    return JSON.parse(readFileSync(out, "utf8")) as VitestJson;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const typechecks = (): boolean => spawnSync(npx, ["tsc", "--noEmit"], { cwd: ROOT, shell: true, stdio: "ignore" }).status === 0;

const failedTests = (r: VitestJson): string[] =>
  r.testResults.flatMap((f) =>
    f.assertionResults
      .filter((a) => a.status === "failed")
      .map((a) => `${f.name.replace(/\\/g, "/").split("/tests/")[1] ?? f.name} › ${a.fullName}`),
  );

interface Outcome { id: string; tool: string; bug: string; status: "killed" | "survived" | "invalid"; killedBy: string[] }

function run(m: Mutation): Outcome {
  const path = join(ROOT, m.file);
  const original = readFileSync(path, "utf8");
  let mutated = original;
  for (const e of m.edits) {
    const count = mutated.split(e.find).length - 1;
    if (count !== 1) throw new Error(`${m.id}: expected exactly one occurrence in ${m.file}, found ${count}: ${e.find.slice(0, 80)}`);
    mutated = mutated.replace(e.find, e.replace);
  }
  writeFileSync(path, mutated);
  try {
    if (!typechecks()) return { id: m.id, tool: m.tool, bug: m.bug, status: "invalid", killedBy: [] };
    const killedBy = failedTests(vitest());
    return { id: m.id, tool: m.tool, bug: m.bug, status: killedBy.length ? "killed" : "survived", killedBy };
  } finally {
    writeFileSync(path, original);
  }
}

const only = process.argv.slice(2);
const selected = only.length ? MUTATIONS.filter((m) => only.includes(m.id)) : MUTATIONS;

if (!typechecks()) throw new Error("the unmutated source does not type-check");
const baseline = vitest();
if (baseline.numFailedTests > 0) throw new Error(`baseline has ${baseline.numFailedTests} failing tests; fix them first`);
console.error(`baseline: ${baseline.numPassedTests}/${baseline.numTotalTests} tests pass`);

const outcomes: Outcome[] = [];
for (const m of selected) {
  const o = run(m);
  outcomes.push(o);
  console.error(`${o.status.padEnd(8)} ${o.id.padEnd(6)} ${o.bug}${o.killedBy.length ? ` (${o.killedBy.length} tests)` : ""}`);
}

if (only.length === 0) {
  const killed = outcomes.filter((o) => o.status === "killed").length;
  const suites = new Map<string, number>();
  for (const f of baseline.testResults) {
    const suite = (f.name.replace(/\\/g, "/").split("/tests/")[1] ?? "").split("/")[0] ?? "";
    suites.set(suite, (suites.get(suite) ?? 0) + f.assertionResults.length);
  }
  mkdirSync(RESULTS, { recursive: true });
  writeFileSync(join(RESULTS, "mutations.json"), JSON.stringify({ baseline: { passed: baseline.numPassedTests, total: baseline.numTotalTests }, outcomes }, null, 2) + "\n");
  const md = [
    "# Contract tests and mutation results",
    "",
    "Generated by `npm run mutate` from a real run; do not edit by hand. Release `data-2026-10-07-67efd3d2`.",
    "",
    "## Test suites",
    "",
    "| Suite | Tests | What it runs against |",
    "|---|---:|---|",
    `| unit | ${suites.get("unit") ?? 0} | pure helpers, the release verification chain, network retry |`,
    `| contract | ${suites.get("contract") ?? 0} | each tool through a real MCP client, over fixture slices of the release |`,
    `| e2e | ${suites.get("e2e") ?? 0} | the server's tool list, annotations and text output |`,
    `| release | ${suites.get("release") ?? 0} | the real pinned release, recomputed against its \`check_values.json\` |`,
    `| **total** | **${baseline.numTotalTests}** | all passing |`,
    "",
    "## Mutations",
    "",
    `Each mutant plants one realistic bug, must still type-check, and must make at least one test fail. **${killed} of ${outcomes.length} killed.**`,
    "",
    "| ID | Tool | Planted bug | Result | Caught by |",
    "|---|---|---|---|---|",
    ...outcomes.map(
      (o) =>
        `| ${o.id} | ${o.tool} | ${o.bug} | ${o.status} | ${o.killedBy.length ? `${o.killedBy.length} test${o.killedBy.length === 1 ? "" : "s"}, e.g. ${o.killedBy[0]?.replace(/\|/g, "\\|")}` : "—"} |`,
    ),
    "",
  ].join("\n");
  writeFileSync(join(RESULTS, "contract-tests.md"), md);
  console.error(`\n${killed}/${outcomes.length} killed; wrote docs/results/contract-tests.md`);
  if (killed !== outcomes.length) process.exitCode = 1;
}
