// Generated by scripts/make-fixtures.ts — do not edit. Regenerate when the default pin moves.
import type { ReleasePin } from "../../src/release.js";

export const FIXTURE_PIN: ReleasePin = {
  "tag": "fixture-data-2026-10-07-67efd3d2",
  "manifestSha256": "6e5b535f833f1a4f64604a313e904170596d1118528f08980192ad8b8126e09a"
};
export const FIXTURE_CODES = ["470","10011","12002","70553","73721","99213","99214","J1885"] as const;
